name: git action test

on:
  push:
    branches:
    - main

jobs:
  workload-identity-connection:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '**projects/452492517379/locations/global/workloadIdentityPools/abata-p-service-wip/providers/abata-p-service-wip-github-abata**'
        service_account: 'gitaction@abata-test-384402.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK-2'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
